<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CK4OP8F" failures="1" tests="4" name="Test" time="55.456" errors="0" timestamp="2022-10-11T19:55:11 IST">
  <testcase classname="com.SauceDemo.TestClasses.TC01_VerifyLoginFunctionality" name="verifyLoginFunctionality" time="1.044"/>
  <testcase classname="com.SauceDemo.TestClasses.TC02_VerifyLogOutFunctionality" name="verifyLOgOutFunctionality" time="1.977"/>
  <testcase classname="com.SauceDemo.TestClasses.TC03_VerifyBagProductFunctionality" name="verifyBagProductFunctionality" time="1.119"/>
  <testcase classname="com.SauceDemo.TestClasses.TC04_VerifyAllProductFunctionality" name="verifyAllProductFunctionality" time="0.886">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.SauceDemo.TestClasses.TC04_VerifyAllProductFunctionality.verifyAllProductFunctionality(TC04_VerifyAllProductFunctionality.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyAllProductFunctionality -->
</testsuite> <!-- Test -->
